# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Thun888
subtitle: 夏日当空，心如深渊 | Thun888's Blog
description: 夏日当空，心如深渊 | Thun888's Blog
keywords: 夏日当空，心如深渊 | Thun888's Blog
author: thun888
avatar: /img/avatar.webp
language: zh-CN
timezone: ''

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://blog.hzchu.top
permalink: :title/
permalink_defaults:
pretty_urls:
  trailing_index: false # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: false # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
htalk_dir: htalk
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: "yandex_26edef25b1a67b8a.html"

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: stellar



# 谷歌、百度站点地图生成
Plugins:
- hexo-generator-baidu-sitemap
- hexo-generator-sitemap

baidusitemap:
    path: baidusitemap.xml
sitemap:
    path: sitemap.xml

search:
  path: search.xml
  field: post
  format: html
  limit: 10000

# hexo-neat
# 博文压缩
neat_enable: true
# 压缩html
neat_html:
  enable: true
  exclude:
# 压缩css  
neat_css:
  enable: true
  exclude:
    - '**/*.min.css'
# 压缩js
neat_js:
  enable: true
  exclude:
    - '**/*.min.js'

# Post wordcount display settings
# Dependencies: https://github.com/willin/hexo-wordcount
post_wordcount:
  item_text: true
  wordcount: true         # 单篇 字数统计
  min2read: true          # 单篇 阅读时长
  totalcount: true       # 网站 字数统计
  separated_meta: true
  
# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repo: 
    github: https://thun888:ghp_JpFfSRWxN*************T37oL9zvo3Q49kT@github.com/thun888/thun888.github.io.git,master
    
  branch: master
  message: "Build at {{ now('YYYY-MM-DD HH:mm:ss Z') }}"

service_worker:
  maximumFileSizeToCacheInBytes: 10485760
  staticFileGlobs:
  - public/**/*.{js,html,css,png,jpg,gif,svg,eot,ttf,woff,woff2}
  stripPrefix: public
  verbose: true
  runtimeCaching:
    - urlPattern: /*
      handler: cacheFirst
      options:
        origin: jsd.onmicrosoft.cn
    - urlPattern: /*
      handler: cacheFirst
      options:
        origin: onep.hzchu.top
    - urlPattern: /*
      handler: cacheFirst
      options:
        origin: raw.hzchu.top
    - urlPattern: /*
      handler: cacheFirst
      options:
        origin: blog.hzchu.top
    - urlPattern: /*
      handler: cacheFirst
      options:
        origin: k.hzchu.top
    - urlPattern: /*
      handler: cacheFirst
      options:
        origin: jsd.hzchu.top
        
dynamic_codeblock:
  loading: true
  showsupporter: true
  api: https://hightlight-code-api.hzchu.top/api/v1/generate
  css: https://jsd.hzchu.top/gh/thun888/assets@master/files/pygments-css/default.css
  
# hexo-safego安全跳转插件
# see https://blog.qyliu.top/posts/1dfd1f41/
hexo_safego:
  enable: true  # 是否启用 hexo-safego 插件
  enable_base64_encode: true  # 是否启用 Base64 编码链接
  enable_target_blank: true  # 是否在跳转链接中添加 target="_blank"
  url_param_name: 'u'  # URL 参数名，用于生成跳转链接
  html_file_name: 'go.html'  # 跳转页面文件名
  ignore_attrs:  # 需要忽略的链接属性列表
    - 'data-fancybox'
  apply_containers:  # 容器 ID 列表，如果为空则匹配整个 body
    - '.md-text'
  domain_whitelist:  # 域名白名单列表，包含白名单中的域名的链接将被忽略
    - 'hzchu.top'
  apply_pages:  # 生效页面路径列表，只有在这些页面上才会对链接进行处理
    - '/2024/'
    - '/2023/'
    - '/2022/'
    - '/2021/'
    - '/2020/'
    - '/2019/'

    - '/wiki/'
  avatar: /img/avatar.webp  # 头像图片链接
  title: "thun888"  # 标题
  subtitle: "安全中心"  # 副标题
  darkmode: true  # 是否启用夜间模式
  debug: false  # 是否启用调试模式，开启后会输出详细的调试信息